<?php

/**
 *  Roadsend SiteManager
 *******************************************************************
 *  Copyright (c) 2001-2003 Roadsend, Inc.(http://www.roadsend.com)
 *******************************************************************
 *
 * This source file is subject to version 1.0 of the Roadsend Public
 * License, that is bundled with this package in the file
 * LICENSE, and is available through the world wide web at
 * http://www.roadsend.com/license/rpl1.txt
 *
 *******************************************************************
 * Author(s): Shannon Weyrick (weyrick@roadsend.com)
 *
 */

/**
 *
 *
 *  directives:
 *
 *   secondSelect   - should seconds be displayed
 *
 *   hourFormat     - 12 hour or 24 hour in display
 *   hourStart      - 0-24 range for time
 *   hourEnd        - 0-24 range for time is 24 hours by default but can be truncted
 *
 *   minuteType   - increments (5,10,15,30 ect)
 *
 *   time MUST be in format HH:MM:SS
 *
 * @author Shannon Weyrick <weyrick@roadsend.com>
 * @package roadsend_siteManager
 * @subpackage siteManager_smartForm
 */
class timeXEntity extends timeEntity {


    }



?>